import './globals.css'

import type { Metadata } from 'next'

import { CognitoAuthProvider } from '@/providers/CognitoAuthProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <CognitoAuthProvider>{children}</CognitoAuthProvider>
      </body>
    </html>
  )
}
